network: sustainers.network
routers:
  - network:
    key:
      id:
      secretName:
vendors:
  cloud:
    gcp:
      projects:
        production: production-271815
        sandbox: sandbox-271815
        staging: staging-271815
        development: development-271815
      computeUrlIds:
        production:
        sandbox:
        staging:
        development: 75tpixyafq
      dnsZone: network
      secretsBuckets:
        production:
        sandbox:
        staging:
        development: development-secrets-271815
      rolesBuckets:
        production:
        sandbox:
        staging:
        development: development-roles-271815
      defaults:
        region: us-central1
        memory: 128Mi
        memoryOverrides:
          event-store: 256Mi
          view-store: 256Mi
  viewStore:
    mongodb:
      users:
        production:
        sandbox:
        staging:
        development: blossm
      hosts:
        production:
        sandbox:
        staging:
        development: view-store-sebjf.gcp.mongodb.net
      protocol: mongodb+srv
  eventStore:
    mongodb:
      users:
        production:
        sandbox:
        staging:
        development: blossm
      hosts:
        production:
        sandbox:
        staging:
        development: event-store-7kjnk.gcp.mongodb.net
      protocol: mongodb+srv
  texting:
    twilio:
      testReceivingPhoneNumber:
        production:
        sandbox:
        staging:
        development: "+12018018796"
      sendingPhoneNumber:
        production:
        sandbox:
        staging:
        development: "+16122237366"
defaults:
  viewStore: mongodb
  eventStore: mongodb
  cloud: gcp
  texting: twilio
